---
version: "3"

vars:
  OUT: "bin/game" 

tasks:
  default:
    desc: inject game
    # deps: [game]
    cmds:
      - odin build ptrace/ -out=bin/injector
      - sudo ./bin/injector

  game:
    desc: Run the Odin game
    cmds:
      - odin run game/ -out={{.OUT}}

  build:
    desc: Build the Odin game
    cmds:
      - odin build . -out={{.OUT}}

  payload:
    desc: Build the payload
    cmds:
      - odin build payload/ -build-mode:shared -out:payload/payload.so
