---
version: "3"

vars:
  OUT: "bin/external"
  # karl2d game variables
  INT_ADDR: 0x53A9F8
  INT2_ADDR: 0x7FFDFBE95F60

tasks:
  default:
    desc: Run the odin external cheat
    deps: [build]
    cmds:
      - sudo ./{{.OUT}} {{.INT_ADDR}} {{.INT2_ADDR}}

  build:
    desc: Build the Odin external
    cmds:
      - odin build . -out={{.OUT}}
